services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: salim
      POSTGRES_PASSWORD: 2002
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: Conferences
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local